version: '3.8'

services:
  # Servicio de la Base de Datos MySQL
  tecnihidros-db:
    image: mysql:8.0
    container_name: tecnihidros_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: tecnihidros_bd
    ports:
      - "3306:3306"
    volumes:
      volumes:
        - mysql_data:/var/lib/mysql
        - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  # Interfaz Web para ver las tablas (phpMyAdmin)
  tecnihidros-admin:
    image: phpmyadmin:latest
    container_name: tecnihidros_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: tecnihidros-db
      MYSQL_ROOT_PASSWORD: root_password_123
    depends_on:
      - tecnihidros-db

volumes:
  mysql_data: